title: Memic Orbit Limited
description: "Memic Orbit Ltd website"
url: "https://memicorbit.com"
logo: "/images/memic-orbit.png"
locale: "en-GB"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
images:       /images
include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true     
      comments: false
      share: false
      related: false             
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
plugins:
  - jekyll-feed
  - jekyll-relative-links
